AvaloniaUI/avaloniaui.net

wwwroot/guides/quickstart.md

The previous instructions were wrong (you need to use "dotnet new -i", not "dotnet install -i" and the templates no longer (never?) existed in Nuget, redirecting to the template repo which has a functional explanation of installation.

Fix template installation instructions for dotnet core

---

wwwroot/architecture/nuget.md
wwwroot/architecture/project-structure.md
wwwroot/assets/css/override.less
wwwroot/blog/2015-02-16-avalonia-properties.md
wwwroot/blog/2015-09-21-avalonia-alpha2.md
wwwroot/blog/2015-12-03-avalonia-alpha3.md
wwwroot/blog/2018-02-18-avalonia-beta1.md
wwwroot/blog/2018-10-09-avalonia-native-osx.md
wwwroot/contributing/build.md
wwwroot/contributing/contributing.md
wwwroot/docs/animations/index.md
wwwroot/docs/animations/keyframe.md
wwwroot/docs/animations/transitions.md
wwwroot/docs/authoring-controls/defining-properties.md
wwwroot/docs/authoring-controls/types-of-control.md
wwwroot/docs/binding/binding-from-code.md
wwwroot/docs/binding/binding-to-commands.md
wwwroot/docs/binding/binding-to-controls.md
wwwroot/docs/binding/bindings.md
wwwroot/docs/binding/converting-binding-values.md
wwwroot/docs/controls/border.md
wwwroot/docs/controls/button.md
wwwroot/docs/controls/menu.md
wwwroot/docs/logging.md
wwwroot/docs/quickstart/create-new-project.md
wwwroot/docs/quickstart/from-wpf.md
wwwroot/docs/quickstart/intro-to-xaml.md
wwwroot/docs/styles/selectors.md
wwwroot/docs/styles/styles.md
wwwroot/docs/templates/datatemplate.md

Added disclaimer for the animations features.
Fix all headers so that they are addressable via the right sidebar of the website. 
Also fix the Style `Is` selector syntax.

Numerous markdown fixes.

---

azure-pipelines.yml

Azure DevOps has a bug where publishing build artifacts from PRs from forks will fail with a permissions error.

Conditionally disable artifact publishing in PRs from Forks

---

.gitignore
README.md
azure-pipelines.yml
build.cmd
fast-buld-without-api.cmd
serve.cmd
wwwroot/_NavBar.cshtml

We've been using Wyam 1.0. We should upgrade to the newest version which is deployed via a .NET Core Tool.
Additionally, I noticed that our source for the API docs gen wasn't updated to 0.7.0, so I updated that as well.

Upgrade To Wyam 2.1.1 and API docs to 0.7.0

---

wwwroot/docs/tutorial/creating-a-view.md
wwwroot/docs/tutorial/creating-the-project.md

Updates dotnet command line parameters and outputs to be consistent with clarifications as necessary.
- Project creation command had wrong template name
- Project created file hierarchy was not consistent with current outputs
- View creation steps don't mention default rather than specific namespace when using command line
- Updated project creation template name
- Updated project hierarchy listing with additional details for new files
- Warning note about the needing to change the default namespace before compiling.

Tutorial update

---

wwwroot/docs/binding/datacontext.md

Fixes a broken link to the 'create new project' in datacontext.md
points to a non-existent page at http://avaloniaui.net/docs/binding/create-new-project.md
Points to the actual page at http://avaloniaui.net/docs/quickstart/create-new-project

Fix broken link to 'create new project' in datacontext.md

---

wwwroot/contributing/build.md

Adds additional instructions for building Avalonia source on Linux and macOS
Leaves out details about dependency tools and libraries
Fully describes the dependencies and additional build steps which previously required foreknowledge or discussions with developers on Gitter.

Update build.md with more specific Linux/macOS instructions

---

wwwroot/docs/quickstart/create-new-project.md

As far as I can tell `avalonia.app.mvvm` has never been the short name for the template?

Change avalonia.app.mvvm to avalonia.mvvm

---

wwwroot/docs/styles/resources.md

I tested it and StaticResource successfully finds the resource placed in App.xaml (Application.Resources) - is this note outdated or am I wrong?
I don't know why GitHub sees last line as a change - nothing changed there.

Remove outdated note

---

wwwroot/docs/tutorial/wiring-up-views.md

Changes "Program.cs" to "App.xaml.cs" in wiring-up-views.md
Incorrectly states that "You'll remember that in **Program.cs** we assigned an instance of MainWindowViewModel to the window's DataContext property."
Changed to "You'll remember that in **App.xaml.cs** we assigned an instance of MainWindowViewModel to the window's DataContext property."

Fixed typo in wiring-up-views.md

---

wwwroot/docs/packing/index.cshtml
wwwroot/docs/packing/macOS.md

Adds an article talking about how to create, sign, and notarize a Avalonia macOS `.app` application. I added it as it's own docs subsection in case someone wants to write an article on packing up a Linux or Windows app at some point.
There is currently no centralized documentation on this subject.
The documentation is added! 😄

Add article on packing macOS applications

---

wwwroot/docs/tutorial/wiring-up-views.md

Fixed typo about DataContext's location.
Fixed anchor link to current heading.
Tutorial says DataContext is in `Program.cs` it is not.
Tutorial is updated with correct references.

Tutorial Typo: DataContext is in App.xaml.cs

---

wwwroot/contributing/contributing.md
wwwroot/index.cshtml

As part of onboarding to the .NET foundation we need to add a link to the foundation and a link to the code of conduct.

Added info required by .NET foundation

---

wwwroot/docs/layout/alignment-margins-padding.md

Fixed broken images due to wrong file extension .PNG in uppercase while they should be lowercase
Images do not render in the browser
Images can render in the browser

#119 Fixed broken images due to wrong file extension

---

wwwroot/docs/quickstart/intro-to-xaml.md

In [Introduction to XAML / Content Properties](https://avaloniaui.net/docs/quickstart/intro-to-xaml#content-properties) fix typo link to the `Button.Content`
Link conducts on this address [`https://avaloniaui.net/docs/quickstart/api/Avalonia.Controls/ContentControl/4B02A756`](https://avaloniaui.net/docs/quickstart/api/Avalonia.Controls/ContentControl/4B02A756) 
Link conducts on this address [`https://avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756`](https://avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756)

Fix typo link to the Button.Content

---

wwwroot/docs/controls/combobox.md
wwwroot/docs/controls/viewbox.md

Fixes an incorrect page title used for `Viewbox` and fixes the links found in `ComboBox` and `Viewbox`. Closes #124.
See #124.
- The duplicate `Expander` entry in the sidebar is fixed, and now shows `Viewbox` instead
- Source code link for `Viewbox.cs` has been corrected
- Labels for the source code links to `ComboBox.cs` and `Viewbox.cs` have been fixed
I've tried to match the formatting seen in other `.md` files, so there's also some whitespace changes in `combobox.md`.

#124: Fix link labels and titles for ComboBox and Viewbox

---

src/AvaloniaUI.Net/Pages/Shared/_DocsLayout.cshtml
src/AvaloniaUI.Net/Pages/Shared/_Head.cshtml
src/AvaloniaUI.Net/Pages/Shared/_Layout.cshtml

Moves the doctype and html opening tags to the respective layouts, this prevents errors/warnings from showing and help with the indentation because the file is properly formatted.
Also, semantically the head partial now only contains the head tag.
IDE can't properly indent and an error of no matching opening tag is shown
IDE does not show the error, formatting works properly on those files

Move some tags to prevent missing tag error in IDE and allow formatting

---

src/AvaloniaUI.Net/wwwroot/css/hero.css

The hero styles were slightly modified to adapt better to medium and small screens .
Modifications to hero.css, padding was reduced and classes inside media queries were created. 
Columns on the hero section look narrow in small screens. As reported in #139. This happens in contributing and support pages.
Hero columns are more legible and responsive. This happens in contributing and support pages.

Hero styles modified solution to #139

---

src/AvaloniaUI.Net/Services/MarkdownDocumentLoader.cs

- Closes #153.
- Closes #157.
Please see the comments in the code for the explanation of the current behavior and of my fix.
I should say that the current parser behavior isn't 100% clear to me (why does it say that the document starts *before* `---`? who knows), but I've verified that all the blog posts (both the ones that had troubles and the ones that had no beforehand) render correctly after this fix.
Probably we could migrate away from YAML if we only use it for simple key-value reading, because this is quickly getting out of hand.

Fix #157: rewind a stream reader after reading a YAML preamble

---

src/AvaloniaUI.Net/wwwroot/docs/controls/combobox.md

Fixes opening in markdown parameters
http://avaloniaui.net/docs/controls/combobox shows its title as Undefined
The title correctly shows as ComboBox

Fixes combobox title showing as undefined

---

src/AvaloniaUI.Net/Pages/Shared/_Head.cshtml

Adds a meta description for SEO and to be used by Search Engines.
There is no tag and the current description in google is the following
There is a description within the recommended length that will eventually show up in Google. The description was crafted between the one used in the site and the one used in the Github project page.

Adding meta description tag

---

src/AvaloniaUI.Net/Pages/Shared/_Navbar.cshtml

Adds an attribute to the links that open in a target="_blank" which seems to be unsafe as reported by lighthouse
There is a regular link which triggers a warning in lighthouse.
It was added the attribute rel="noopener" to a couple of links

Secure external links

---

src/AvaloniaUI.Net/wwwroot/docs/packing/macOS.md

Forgot to state that you need to put your .app in a .zip to notarize it.
Closes https://github.com/AvaloniaUI/Avalonia/issues/4338
The directions are wrong. 🤪
The directions are now fixed!

Fix macOS packing notarization directions

---

src/AvaloniaUI.Net/wwwroot/docs/controls/textbox.md

A simple casing error in the docs title
It shows Textbox
Now it shows TextBox

Title casing typo in TextBox docs

---

src/AvaloniaUI.Net/Pages/Shared/_Head.cshtml

Removes unused Font Awesome reference as reported in #174 
Font Awesome is loaded from CDN
The reference is removed as it is not used in the whole site.
Fixes #174

Removing unused font-awesome #174

---

src/AvaloniaUI.Net/Pages/Shared/_Head.cshtml

@Carlos487 had to revert #174 - font awesome is used for the expand chevrons in the docs sidebar:
https://github.com/AvaloniaUI/avaloniaui.net/blob/master/src/AvaloniaUI.Net/wwwroot/css/docs.css#L89
Reverts AvaloniaUI/avaloniaui.net#182

Revert "Removing unused font-awesome #174"

---

src/AvaloniaUI.Net/wwwroot/css/content.css

Use a more readable line spacing for docs and blog posts, as suggested in #136

Update line-height to 1.75 for docs/blog posts.

---

src/AvaloniaUI.Net/Pages/Shared/_Head.cshtml
src/AvaloniaUI.Net/Pages/Shared/_Navbar.cshtml

Updated FontAwesome version, loading full version to access more icons, which can be useful in other areas of the site and adding Github icon to the menu.
Loading partial css from font-awesome, no icon on menu.
Loading full updated FontAwesome version and adding Github icon to the menu, as other

Updating FontAwesome and menu icon

---

src/AvaloniaUI.Net/wwwroot/docs/controls/tabstrip.md

Fixes the link to the API Reference for the `TabStrip` control.
Link is broken.
Link now points to correct location.

Fix TabStrip API Reference Link

---

src/AvaloniaUI.Net/Services/MarkdownDocumentLoader.cs
src/AvaloniaUI.Net/wwwroot/docs/binding/attached-properties.md

Fix 'Mapping values are not allowed in this context' in YamlDotNet. Also, for the future, I used this advice https://github.com/aaubry/YamlDotNet/issues/376#issuecomment-500478360
Parsing error occurs in my conditions. On server page of https://avaloniaui.net/docs/binding/attached-properties :
Parses without errors
Fixes #204

Fix dash typo

---

src/AvaloniaUI.Net/Pages/Index.cshtml

The "Find out more" link under XAML on the homepage was a broken link. Fixes that.

Fix XAML "find out more" link on homepage.

---

.gitignore
src/AvaloniaUI.Net/wwwroot/docs/styles/styles.md

Fix ref to `Control.Styles` (Inherited from `StyledElement`)
404 Not Found: http://reference.avaloniaui.net/api/Avalonia.Controls/Control/4145DF25 (after #209 there will be http)
Work: http://reference.avaloniaui.net/api/Avalonia/StyledElement/0A46A84A

Fix ref to Control.Styles

---

src/AvaloniaUI.Net/Startup.cs

Use http for reference api (I do not know how to more correctly specify to redirect to http)
For example https://avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756 redirected to https://reference.avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756
https://avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756 redirected to http://reference.avaloniaui.net/api/Avalonia.Controls/ContentControl/4B02A756

Use http for reference api

---

src/AvaloniaUI.Net/wwwroot/docs/quickstart/packages.md

Previously it was:
- Missing an `a`
- Displayed as a link but there's not much use visiting it in the browser

Fix PR feed URL.

---

src/AvaloniaUI.Net/wwwroot/docs/controls/image.md

- Fixed bitmap converter target type check.
The converter fails because the type of `Image.Source` was changed: `IBitmap` -> `IImage`.
As the converter returns a `Bitmap`, accept any target type assignable from it.
Fixes #235

Fixed bitmap converter target type check

---

src/AvaloniaUI.Net/Pages/Docs/Index.cshtml
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/add-controls.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/add-dialog-content.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/add-to-user-collection.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/create-a-modern-window.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/create-project.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/display-images.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/index.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/initialisation.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/opening-dialog.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/searching-albums.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/setup.md
src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/summary.md
src/AvaloniaUI.Net/wwwroot/docs/input/events.md
src/AvaloniaUI.Net/wwwroot/docs/tutorial/index.md

A few fixes to the Advanced Tutorial:
- Fix article ordering
- Fix XAML code blocks
- Fix some image links which referred to @danwalmsley's local machine
- Add link to the tutorial repo
Also a more general fix:
- Display the documentation article title in browser title bar

Advanced tutorial fixes

---

src/AvaloniaUI.Net/wwwroot/docs/packing/macOS.md

I don't know if it's a typo or anything, but [CFBundlePackageType](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundlepackagetype) says `For apps, the code is APPL`. And the [Bundle Structures](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html) says `For applications, the value of this key is always the four-character string APPL.`
I've also created PR to [dotnet-bundle](https://github.com/egramtel/dotnet-bundle/pull/6).
`AAPL` -> `APPL`

Fix CFBundlePackageType
