wwwroot/blog/2018-02-18-avalonia-beta1.md
use `Tag` instead of `Text` in the binding
=> Fix $parent shorthand example

wwwroot/blog/2018-10-09-avalonia-native-osx.md
1) Adds a screenshot.
2) updates the recommended nuget package versions.
=> minor update to blog post

wwwroot/docs/styles/selectors.md
Feature added by https://github.com/AvaloniaUI/Avalonia/pull/2268.
=> Added docs for `:not()` selector.

wwwroot/docs/templates/datatemplates-in-code.md
Code sample of data template in code was wrong.
=> Fixed code sample.

wwwroot/blog/2018-10-30-avalonia-0.8-release.md, wwwroot/docs/animations/keyframe.md, wwwroot/docs/animations/transitions.md
Adds a blog post and updates some docs for 0.8.0 release.
=> 0.8.0 release

wwwroot/blog/2018-10-30-avalonia-0.7-release.md, wwwroot/docs/binding/converting-binding-values.md, wwwroot/docs/quickstart/from-wpf.md
Fix various broken links.
Fixes #40
Fixes #44
Fixes #46
=> Fix various broken links

wwwroot/docs/controls/textbox.md
=> Tooltip -> Textbox

wwwroot/docs/controls/button.md
Makes it easier to check the code from the doc
=> Add source code link for Button control

wwwroot/assets/css/adminlte/_core.less, wwwroot/assets/css/bootstrap/variables.less, wwwroot/assets/css/highlight.css, wwwroot/assets/css/override.less, wwwroot/assets/css/theme/theme.less, wwwroot/blog/2017-05-08-avalonia-alpha5.md, wwwroot/contributing/contributing.md, wwwroot/docs/animations/index.md, wwwroot/docs/authoring-controls/defining-properties.md, wwwroot/docs/authoring-controls/index.cshtml, wwwroot/docs/binding/binding-from-code.md, wwwroot/docs/binding/binding-to-commands.md, wwwroot/docs/binding/change-notifications.md, wwwroot/docs/binding/datacontext.md, wwwroot/docs/binding/reactiveui.md, wwwroot/docs/binding/templatebinding.md, wwwroot/docs/controls/index.cshtml, wwwroot/docs/logging.md, wwwroot/docs/quickstart/index.cshtml, wwwroot/docs/quickstart/logging.md, wwwroot/docs/styles/styles.md, wwwroot/docs/templates/index.cshtml
- Fix the order of sections in the sidebar
- Added a page on change notifications. Fixes #45
- Explain how to terminate bindings. Fixes #47
- Fix `CommandParameter` examples. Fixes #49
- Update logging docs
- Update snippet from template in "Data Context" doc
- Clarify a few things in "Data Context" doc
- Clarify the fact that `TemplateBinding` doesn't work with property paths
Depends on #57
=> Various fixes

wwwroot/assets/css/adminlte/_core.less, wwwroot/assets/css/bootstrap/variables.less, wwwroot/assets/css/highlight.css, wwwroot/assets/css/override.less, wwwroot/assets/css/theme/theme.less, wwwroot/blog/2017-05-08-avalonia-alpha5.md, wwwroot/contributing/contributing.md, wwwroot/docs/authoring-controls/defining-properties.md, wwwroot/docs/binding/binding-from-code.md, wwwroot/docs/logging.md
Tweaked the theme to try and make it a bit more readable:
- More whitespace between paragraphs
- Removed italic/color in headers and give them more spacing
- Give code blocks a dark background and more spacing
Before:
After:
=> Theme tweaks

wwwroot/docs/tutorial/adding-new-items-2.md, wwwroot/docs/tutorial/adding-new-items.md
=> Fix broken links

wwwroot/docs/controls/contentcontrol.md, wwwroot/docs/controls/usercontrol.md, wwwroot/docs/controls/window.md, wwwroot/docs/quickstart/assets.md, wwwroot/docs/quickstart/from-wpf.md, wwwroot/docs/quickstart/logging.md, wwwroot/docs/quickstart/usercontrol.md, wwwroot/docs/quickstart/window.md
Adds documentation for `Window` and `UserControl`: both to the "Quickstart" section and the "Standard Controls" section.
Depends on #63
=> Added some docs on Window and UserControl

wwwroot/docs/animations/keyframe.md
Replaced obsolete RepeatCount property with IterationCount
Maybe the wording could be adjusted as well but I wasn't creative enough :)
=> Update repeat section in animation docs

wwwroot/docs/controls/listbox.md
=> Added some basic ListBox docs.

wwwroot/docs/reactiveui/activation.md, wwwroot/docs/reactiveui/routing.md, wwwroot/docs/reactiveui/suspension.md
Documentation for `AutoSuspendHelper` is added. 
Currently, there is no documentation file describing how to use the [ReactiveUI Suspension](https://reactiveui.net/docs/handbook/data-persistence/) feature.
The documentation file has been added.
=> Document AutoSuspendHelper and Friends

wwwroot/docs/quickstart/devtools.md
I've not added any detail on how to use DevTools itself as it's going to be revamped very soon.
=> Added basic docs about DevTools.

wwwroot/docs/animations/keyframe.md, wwwroot/docs/animations/transitions.md, wwwroot/docs/binding/binding-to-commands.md, wwwroot/docs/controls/contentcontrol.md, wwwroot/docs/quickstart/intro-to-xaml.md, wwwroot/docs/styles/resources.md, wwwroot/docs/styles/styles.md, wwwroot/docs/templates/datatemplate.md, wwwroot/docs/tutorial/creating-model-viewmodel.md
Several xaml examples was changed to corrects a xml syntax.
=> Small fixes for several xaml examples in docs.

wwwroot/docs/tutorial/creating-model-viewmodel.md
Updates the tutorial to 0.9, making the changes required for application lifetime support.
=> Update tutorial to 0.9

wwwroot/_Master.cshtml, wwwroot/docs/binding/change-notifications.md, wwwroot/docs/binding/converting-binding-values.md, wwwroot/docs/styles/selectors.md, wwwroot/docs/styles/styles.md
- Fix `favicon` location. Fixes #74 
- Added info on collection change notifications. Fixes #89 
- Added info on built-in converters. Fixes #99
=> Various small updates

wwwroot/docs/controls/combobox.md
Add more documentation for the combobox page and correct the previous link
Page shows description and link to the wrong source
Additionally it shows examples and common properties, with the correct link to source
=> Added ComboBox information

src/AvaloniaUI.Net/Pages/Contributing.cshtml, src/AvaloniaUI.Net/Pages/Index.cshtml, src/AvaloniaUI.Net/Pages/Support.cshtml
This PR adds the alt attribute to the <img> tags to improve accessibility and SEO.
<img> tags do not contain any alt text.
Images contain alt text describing it purpose which improves accessibility.
=> Add alt attribute to <img> tags

src/AvaloniaUI.Net/wwwroot/css/base.css
Modify the css for the `code` tags that are inside a table. Fixing the issue reported on #141 
The word wraps and makes it difficult to read.
The word is not wrapping, tables are more readable across different resolutions.
=> Fixes tables width issues from #141

src/AvaloniaUI.Net/Pages/Docs/Index.cshtml.cs
Sort documents alphabetically when they have the same Order.
A less manual alternative to #156
What do you think @Carlos487?
=> Sort documents alphabetically when they have the same Order.

README.md
Adds a readme file with instructions
No readme file
A readme file with repo information and instructions
=> Adding a readme file

azure-pipelines.yml, src/AvaloniaUI.Net/AvaloniaUI.Net.csproj
Setting up Azure Pipelines to publish release.
=> Set up release.

src/AvaloniaUI.Net/Pages/Shared/_Navbar.cshtml
Fixes a minor accessibility issue reported in Lighthouse
There is an issue regarding accessibility that can impact SEO as seen in the image
The issue is solved by assigning an aria attribute and the accessibility score is 100
=> Fix accessibility issue

src/AvaloniaUI.Net/Pages/Shared/_Footer.cshtml, src/AvaloniaUI.Net/Pages/Shared/_Head.cshtml
It helps to increase the site performance by moving all the scripts or script request to the footer.
The site performance score in lighthouse around 96. Recommending deferring the load on the Javascript file(s)
The file is requested later at the end of the body and the site scores 100 in all categories of the lighthouse benchmark.
=> Performance improvements

src/AvaloniaUI.Net/wwwroot/docs/quickstart/codebehind.md, src/AvaloniaUI.Net/wwwroot/docs/quickstart/intro-to-xaml.md, src/AvaloniaUI.Net/wwwroot/docs/quickstart/usercontrol.md, src/AvaloniaUI.Net/wwwroot/docs/quickstart/window.md, src/AvaloniaUI.Net/wwwroot/docs/styles/resources.md, src/AvaloniaUI.Net/wwwroot/docs/templates/datatemplate.md, src/AvaloniaUI.Net/wwwroot/docs/tutorial/adding-new-items-2.md, src/AvaloniaUI.Net/wwwroot/docs/tutorial/adding-new-items.md, src/AvaloniaUI.Net/wwwroot/docs/tutorial/creating-a-view.md, src/AvaloniaUI.Net/wwwroot/docs/tutorial/creating-model-viewmodel.md, src/AvaloniaUI.Net/wwwroot/docs/tutorial/creating-the-project.md, src/AvaloniaUI.Net/wwwroot/docs/tutorial/locating-views.md, src/AvaloniaUI.Net/wwwroot/docs/tutorial/wiring-up-views.md
Update the docs to:
- Explain the `.xaml`/`.axaml` situation
- Update the docs to use the `.axaml` extension is it's most likely that a new user will be using VS
=> Update docs with .axaml change.

src/AvaloniaUI.Net/wwwroot/docs/styles/resources.md, src/AvaloniaUI.Net/wwwroot/docs/styles/styles.md
Adds documentation for `StyleInclude`. Closes #160.
There is no documentation on how to use `StyleInclude`.
Documentation has been added. I've also moved up a remark that used to be at the end of the section I added to, since I think it makes more sense for it to be higher up.
=> Styles: Add Documentation for StyleInclude

src/AvaloniaUI.Net/wwwroot/docs/binding/attached-properties.md
Added missing dashes.
missing
there
=> Added missing dashes. However they wend lost

src/AvaloniaUI.Net/wwwroot/docs/tutorial/creating-the-project.md
addressing Issue#202
Please note that I have not been able to test this (or reproduce the problem on localhost) due to "dotnet run" not working.
=> Removing hard coded link to localhost

src/AvaloniaUI.Net/wwwroot/docs/controls/tabcontrol.md
=> Fixing typo indivual to individual

src/AvaloniaUI.Net/wwwroot/docs/tutorial/creating-the-project.md
With the resolution of Issue#204, I found that my previous PR#203 did not have the correct path.  This PR corrects the path.
Fixes #202
=> Corrected path to intro-to-xaml

src/AvaloniaUI.Net/wwwroot/docs/quickstart/intro-to-xaml.md
This PR fixes a documentation typo in `intro-to-xaml.md`.
=> Fix a typo

src/AvaloniaUI.Net/wwwroot/docs/quickstart/assets.md
=> Fix including assets as in templates

src/AvaloniaUI.Net/Pages/Index.cshtml
=> fix partner logo.

src/AvaloniaUI.Net/wwwroot/docs/quickstart/devtools.md
update DevTools  documentation
=> docs(devtools): update docs at release 0.10.0

src/AvaloniaUI.Net/Pages/Shared/_Head.cshtml
This adds social preview images for the Avalonia website.
Currently, there are no open graph images here.
With this change, the open graph image is added.
=> feature: Add Open Graph tags

src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/add-controls.md, src/AvaloniaUI.Net/wwwroot/docs/advanced-tutorial/index.md
=> Add some links to live stream and icons.

index.html, showcase.html, support.html
Bump bootstrap to stable version
bootstrap beta version
bootstrap stable version
=> Bump bootstrap to stable version

index.html, showcase.html, styles.css, support.html
=> update ui, mobile & tablet

index.html
=> Fix 'commercial' spelling

form.html, styles.css
update issue https://github.com/AvaloniaUI/avaloniaui.net/issues/279
=> ui improvements form page on mobile

index.html
=> General fixes
